# Generated by Django 5.0.2 on 2024-02-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listings',
            options={'ordering': ('title',), 'verbose_name_plural': 'Listings'},
        ),
        migrations.AddField(
            model_name='band',
            name='like_new',
            field=models.BooleanField(default=False),
        ),
    ]
